# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.10.0
    hooks:
      - id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
    - id: isort
      args:
        - --profile
        - black
        - --filter-files
-   repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.390
    hooks:
      - id: pyright
        language_version: python3.13
        additional_dependencies:
          - discord.py-self @ git+https://github.com/dolfies/discord.py-self
-   repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
