name: utilbot
services:
    utilbot:
        container_name: utilbot
        build: .
        restart: unless-stopped
        env_file:
          - .env
        volumes:
          - ./dropins:/app/dropins
          - ./cache:/app/cache
